pipelines:
  branches:
    master:
      - step:
          name: Build and Push Docker Image
          deployment: production
          services:
            - docker
          script:
            - export IMAGE_NAME=nexus.npaw.com/publisher-analytics-app:v$BITBUCKET_BUILD_NUMBER-amd64
            - export NEXUS_REPO=nexus.npaw.com
            - echo $NEXUS_PASSWORD | docker login $NEXUS_REPO --username $NEXUS_USERNAME --password-stdin
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME